### PR TITLE
Added Close() to Stmt in sqlx -- this method is on the underlying sqlx type, but was not exposed in the wrapper

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Build failure doesn't look related.

**Comment by eminano** [comment]
Hi! :) 

This is a pretty important change to be able to safely close statements, which at the moment is only possible for ```NamedStmt```. @maplebed can someone from your organisation check this out? It feels like it's been forgotten :(

Thanks a lot! 
Esther

**Comment by maplebed** [comment]
Thanks for the bump @eminano - merged!

**Comment by alex** [comment]
@maplebed thanks!

**Comment by maplebed** [comment]
and for completeness, rolled up in to release v0.4.6

**Pull request merged**
